=encoding utf8

=pod
 
=head1 NAME

=for html <div><img src="https://raw.githubusercontent.com/sbatschelet/SpaceCamp/master/public/img/space-camp.png"></div>

=head1 SYNOPSIS

Space Camp is a container based portable and cloud capable development platform.

=head1 CONFIGURATION

Work in progress

=cut

```
/
`-- home
    `-- sam
        `-- camp10
            |-- .aci/
                 |-- manifest
                 |-- rootfs/
            |-- config/
            |   |-- camp10.service
            |   |-- environment.yml
            |   |-- network.yml
            |-- git-repo/
            |-- README
```
